- hosts: all
  tasks:
   - name: stop container
     shell: docker container stop dockeransible

   - name: remove container
     shell: docker container rm dockeransible

   - name: remove docker image
     shell: docker image rmi mohan03/test-deploy-app
   - name: create new container
     shell: docker container run -itd --name dockeransible -p 9000:80 mohan03/test-deploy-app
